#ifndef TRELIS_IMPORT_MCNP_VERSION_H
#define TRELIS_IMPORT_MCNP_VERSION_H

#define TRELIS_IMPORT_MCNP_VERSION_MAJOR 0
#define TRELIS_IMPORT_MCNP_VERSION_MINOR 1
#define TRELIS_IMPORT_MCNP_VERSION_REV   0

#endif /* TRELIS_IMPORT_MCNP_VERSION_H */
